In [38]:
import numpy as np

test_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

np.random.seed(0)
first_centroid_index = np.random.choice(len(test_array))

centroids_arr = test_array[first_centroid_index]
test_array = np.delete(test_array, first_centroid_index, 0)

print(test_array)
print(centroids_arr)


[[4 5 6]
 [7 8 9]]
[1 2 3]


In [41]:
import pandas as pd

test_df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [71,81,91]])

first_cen_index = np.random.choice(len(test_df))

# test_df["sum"] = test_df.sum(axis=1)
# np.linalg.norm(test_df[0])
#  test_df["min_dist"] = test_df.apply(lambda row: )

a = [[12, 13, 14], [6,7,8]]
test_df["distance"] = test_df.apply(lambda row: min(np.linalg.norm(i - row) for i in a), axis=1) # 2
test_df["ratio"] = test_df["distance"] / sum(test_df["distance"])                # 3
print(test_df)
print("------")
print(np.random.choice(len(test_df), list(test_df["ratio"])))



SyntaxError: unexpected EOF while parsing (1003577456.py, line 17)

In [3]:
from numpy import linalg

print(linalg.eigvals([[2, -1, 0], [-1, 2, -1], [0, -1, 2]]))

# from wiki
print(linalg.eigvals([[4, -30, 60, -35], [-30, 300, -675, 420], [60, -675, 1620, -1050], [-35, 420, -1050, 700]]))


[3.41421356 2.         0.58578644]
[2.58525381e+03 3.71014914e+01 1.66642861e-01 1.47805484e+00]
