In [38]:
import numpy as np

test_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

np.random.seed(0)
first_centroid_index = np.random.choice(len(test_array))

centroids_arr = test_array[first_centroid_index]
test_array = np.delete(test_array, first_centroid_index, 0)

print(test_array)
print(centroids_arr)


[[4 5 6]
 [7 8 9]]
[1 2 3]


In [41]:
import pandas as pd

test_df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [71,81,91]])

first_cen_index = np.random.choice(len(test_df))

# test_df["sum"] = test_df.sum(axis=1)
# np.linalg.norm(test_df[0])
#  test_df["min_dist"] = test_df.apply(lambda row: )

a = [[12, 13, 14], [6,7,8]]
test_df["distance"] = test_df.apply(lambda row: min(np.linalg.norm(i - row) for i in a), axis=1) # 2
test_df["ratio"] = test_df["distance"] / sum(test_df["distance"])                # 3
print(test_df)
print("------")
print(np.random.choice(len(test_df), list(test_df["ratio"])))



SyntaxError: unexpected EOF while parsing (1003577456.py, line 17)

In [4]:
from numpy import linalg, array
from scipy.sparse import csgraph

a = array([[2, -1, 0], [-1, 2, -1], [0, -1, 2], [-1, 2, -1], [0, -1, 2]])

print(linalg.eigh([[2, -1, 0], [-1, 2, -1], [0, -1, 2]]))

print(csgraph.laplacian(a))

# from wiki
print(linalg.eigh([[4, -30, 60, -35], [-30, 300, -675, 420], [60, -675, 1620, -1050], [-35, 420, -1050, 700]]))




(array([0.58578644, 2.        , 3.41421356]), array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
       [-7.07106781e-01,  4.37150316e-16, -7.07106781e-01],
       [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]))
[[-1  1  0]
 [ 1 -2  1]
 [ 0  1 -1]]
(array([1.66642861e-01, 1.47805484e+00, 3.71014914e+01, 2.58525381e+03]), array([[-0.79260829, -0.5820757 ,  0.17918629, -0.02919332],
       [-0.45192312,  0.37050219, -0.74191779,  0.32871206],
       [-0.3224164 ,  0.50957863,  0.10022814, -0.79141115],
       [-0.25216117,  0.51404827,  0.63828253,  0.51455275]]))
